### ISSUE TITLE
Report workload 's actual running state

### ISSUE THREAD

**Issue by michaeldmitry** [canonical/tempo-worker-k8s-operator#20]
### Enhancement Proposal

When a workload is down (i.e Tempo failed to start its service for any reason), the user is not aware of that state since we're reporting it as `active/idle` although the workload is not ready to serve/accept requests. We should have a mechanism to detect when the workload is down and reflect that on the unit's state (e.g: Blocked)

**Comment by PietroPasotti** [comment]
related: https://github.com/canonical/cos-lib/issues/51

**Comment by PietroPasotti** [comment]
we should use a pebble check to constantly monitor the service status

**Comment by michaeldmitry** [comment]
Fixed by https://github.com/canonical/tempo-worker-k8s-operator/pull/22
